language: php

php: [5.4, 5.5, 5.6, hhvm]

matrix:
  allow_failures:
    - php: hhvm

cache:
  directories:
    - vendor

before_script:
  - composer install --prefer-dist --dev

script:
    - ./bin/phpspec run -fpretty
    - ./bin/funk functional
